- name: Check if Custom SELinux Module is Installed
  shell: semodule -l | grep mumble_selinux
  register: module_installed
  ignore_errors: yes

# There should be a more idempotent way to handle this
- name: Install Custom Module
  block:
    - name: Copy TE to VM
      ansible.builtin.copy:
        src: ./files/mumble_selinux.te
        dest: /tmp/

    - name: Convert TE to SELinux Module
      shell: checkmodule -M -m -o /tmp/mumble_selinux.mod /tmp/mumble_selinux.te

    - name: Convert SELinux Module to PP
      shell: semodule_package -o /tmp/mumble_selinux.pp -m /tmp/mumble_selinux.mod

    - name: Install SELinux PP File
      shell: semodule -i /tmp/mumble_selinux.pp
  when: module_installed.rc == 1
